version: '3.8'

services:
  web:
    container_name: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - static:/www/app/staticfiles:rw
      - media:/www/app/media:rw
      - ./backend:/usr/src/app:rw
    ports:
      - "8842:8001"
    restart: always
    networks:
      - main

  nginx:
    container_name: nginx_hci
    build:
      context: ./nginx/
    volumes:
      - static:/home/app/staticfiles:rw
      - media:/home/app/media:rw
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    restart: always
    networks:
      - main
volumes:
  static:
  media:
networks:
  main: